<a href="https://colab.research.google.com/github/Kornel1156/Data-Science/blob/main/01_biblioteka_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Spis Treści :
1. [Podstawy](#scrollTo=Podstawy)
2. [Typy Danych](#scrollTo=Typy_Danych)
3. [Tworzenie Tablic](#scrollTo=Tworzenie_Tablic)
4. [Podstawowe operacje na tablicach](#scrollTo=Podstawowe_operacje_na_tablicach)
5. [Generowanie liczb pseudolosowych](#scrollTo=Generowanie_liczb_pseudolosowych)
6. [Podstawowe funkcje](#scrollTo=Podstawowe_funkcje)
7. [Indeksowanie , wycinanie](#scrollTo=Indeksowanie_wycinanie)
8. [Iteracja po tablicach](#scrollTo=Iteracja_po_tablicach)
9. [Zmiana rozmiaru tablicy](#scrollTo=Zmiana_rozmiaru_tablicy)
10. [Maski](#scrollTo=Maski)
11. [Broadcasting](#scrollTo=Broadcasting)



# Podstawy

In [2]:
import numpy as np                 # importowanie biblioteki numpy
np.__version__                     # sprawdzenie Wersji biblioteki

'2.0.2'

sprawdzenie wszystkich możliwych dubkfju i metod które zawiera biblioteka

In [3]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'arra

aby dowiedziec sie o metodzie albo funkcji która oferuje biblioteka używamy help

In [4]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

1. Podstawowy element biblioteki numpy jest wielowymiarowa tablica

2. cecha charakterystyczna jest jej jednorodny typ tylko taki sam wszystkich elementow

3. osie to wiersze i kolumny czy tez 3 , 4 wymiar w naszym zbiorze , nazywane sa axis



tablica 1D


In [5]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [6]:
print(x)

[1 2 3 4]


In [7]:
type(x) # funkcja type , sprawdza typ obiektu

numpy.ndarray

In [8]:
x.ndim # ilosc wumarow czyli ile wierszy i kolumn albo bardziej wymiarowe przestrzenie danych

1

In [9]:
x.shape # przedstawia ile elementow znajduje sie w kazdym wymiarze n # bo mamy 4 elementy 1 wiersz

(4,)

In [10]:
x.size # liczba wszystkich elementow w calej przestrzeni

4

In [11]:
x.dtype # okresla jakiego typu dane sa reprezentowane przez tablice numpy bo może być tylko jeden konkretny w danym momencie jednakowy typ dla wszystkich


dtype('int64')

In [12]:
x = np.array([1.2,2.3,2.5])

In [13]:
print(x)

[1.2 2.3 2.5]


In [14]:
x.dtype

dtype('float64')

tablica 2D - macierze

In [15]:
x = np.array([[1,2] , [-3 , 1 ]])

In [16]:
x

array([[ 1,  2],
       [-3,  1]])

In [17]:
x.ndim # ilosc wymiarow tablicy

2

In [18]:
x.shape # przedstawia ile elementow znajduje sie w kazdym wymiarze , # bo mamy 1 tablice , 2 kolumny , 2 wiersze

(2, 2)

In [19]:
x.size # calkowita ilosc wartosci

4

In [20]:
x = np.array([[1,2,3],[4,5,6]])

In [21]:
print(x)

[[1 2 3]
 [4 5 6]]


In [22]:
x.shape  # przedstawia ile elementow znajduje sie w kazdym wymiarze

(2, 3)

tablica 3D

In [23]:
x = np.array([
    [[2,3,4],
     [3,5,7]],

    [[4,0,4],
     [4,5,6]],
    ])

In [24]:
x.shape  # ilosc elementow w kazdym wymiarze bo mamy 2 tablice , 2 wiersze , 3 kolumny

(2, 2, 3)

In [25]:
x.ndim

3

In [26]:
x = np.array([
    [[2,3,4],
     [3,5,7]],

    [[4,0,4],
     [4,5,6]],

    [[4,0,4],
     [4,5,6]]
    ])

In [27]:
x.ndim

3

In [28]:
x.shape

(3, 2, 3)

In [29]:
# bo mamy 3 tablice , 2 wiersze , 3 kolumny

# Typy_Danych

Tworzenie tablicy

In [30]:
a = np.array([1.0 , 2.4,3.5])

In [31]:
a.dtype

dtype('float64')

In [32]:
a = np.array([0 ,4,3])

In [33]:
a.dtype

dtype('int64')

* USTAWIENIE DODATKOWEGO PARAMETRU JAKIEGO TYPU JEST TABLICA KTORA AUTOMATYCZNIE USTAWIA NP INT NA FLOAT
* DODATKOWY PARAMETR DZIALA JAK RZUTOWANIE NA WSKAZANY TYP

In [34]:
a = np.array([1, 2,3] , dtype='float') # typ zmiennoprzecinkowy

In [35]:
a

array([1., 2., 3.])

In [36]:
a = np.array([1.895, 2.333,3.345] , dtype='int') # styp staly

In [37]:
a

array([1, 2, 3])

In [38]:
type(a)

numpy.ndarray

In [39]:
a = np.array([1.895, 2.333,3.345] , dtype='complex') # typ urojone

In [40]:
a

array([1.895+0.j, 2.333+0.j, 3.345+0.j])

In [41]:
a.dtype

dtype('complex128')

In [42]:
a = np.array([True , False]) # typ boolowski

In [43]:
a.dtype

dtype('bool')

* (WBUDOWANE TYPY DANYCH jak unisigned int 8 od 0 do 255 ) Tablica reprezentujaca obraz dla pixeli

In [44]:
a = np.array([24,120 , 230] , dtype=np.uint8)

# Tworzenie_Tablic

In [45]:
np.zeros(shape=(4,10)) # tworzy dowolna tablica utworzoną z samych zer

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Dodanie z okresleniem typow naszych wartosci w takiej tablicy

In [46]:
np.zeros(shape=(4,10) , dtype='int') # tworzy dowolna tablica utworzoną z samych zer z typem

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

tablica z samymi jedynkami

In [47]:
np.ones(shape=(5,5) ,  dtype='complex')

array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]])

tworzenie tablic z wartosciami ktore my chcemy

In [48]:
np.full(shape=(4,10) , fill_value=4 , dtype='double') # tworzy dowolna tablica utworzoną z samych zer z typem oraz nasza wartscia

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

wygeneruje dane w zakresie

In [49]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

ustawienie poczatek koniec i co ile

In [50]:
np.arange(start=5 , stop=12)

array([ 5,  6,  7,  8,  9, 10, 11])

In [51]:
np.arange(start=1 , stop=12 , step=3) # dodatkowy parametr definiujacy krok z jakim tworzona jest tablica

array([ 1,  4,  7, 10])

In [52]:
np.arange(start=100 , stop=0 , step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [53]:
np.arange(start=1 , stop=0 , step=-0.02)

array([1.  , 0.98, 0.96, 0.94, 0.92, 0.9 , 0.88, 0.86, 0.84, 0.82, 0.8 ,
       0.78, 0.76, 0.74, 0.72, 0.7 , 0.68, 0.66, 0.64, 0.62, 0.6 , 0.58,
       0.56, 0.54, 0.52, 0.5 , 0.48, 0.46, 0.44, 0.42, 0.4 , 0.38, 0.36,
       0.34, 0.32, 0.3 , 0.28, 0.26, 0.24, 0.22, 0.2 , 0.18, 0.16, 0.14,
       0.12, 0.1 , 0.08, 0.06, 0.04, 0.02])

linspace funkcja ktora tworzy nam zbior wartosci z przedziału początek i koniec który bedzie zawierał rowno podzielone wartosci wedug parametru ilosci przedziałów

* reasumujac dodstniemy num=x wartosci rowno rozlozonych z przedzialu start=a , stop=b

In [54]:
np.linspace(start=0 , stop=1 , num=13)

array([0.        , 0.08333333, 0.16666667, 0.25      , 0.33333333,
       0.41666667, 0.5       , 0.58333333, 0.66666667, 0.75      ,
       0.83333333, 0.91666667, 1.        ])

zmienianiu rozmiaru danych

In [55]:
a = np.arange(15)

In [56]:
a.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [57]:
a.reshape((3, -1)) # -1 do odpowiednia liczba kolumn jaka musi byc czyli python sam dostosuje poprzez -1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [58]:
a.reshape((-1, 3)) # -1 do odpowiednia liczba kolumn jaka musi byc czyli python sam dostosuje poprzez -1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# Podstawowe operacje na tablicach

In [59]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [60]:
a + b # dodawanie element po elemencie

array([ 6,  8, 10, 12])

In [61]:
a - b # odejmowanie element po elemencie

array([-4, -4, -4, -4])

In [62]:
a * b


array([ 5, 12, 21, 32])

In [63]:
a / b  # uwaaga nie mozna dzielic przez 0 wiec tablica nie moze miec zera w mianowniku

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [64]:
# dodanie 3 do kazdego elementu
a + 3


array([4, 5, 6, 7])

In [65]:
# inne i łączone
a + 3*  b

array([16, 20, 24, 28])

In [66]:
# rowniez metody ktore dodaja dwie tablice
np.add(a,b)

array([ 6,  8, 10, 12])

In [67]:
# odejmowanie przez metode
np.subtract(a,b)

array([-4, -4, -4, -4])

In [68]:
# metoda mnożaca dwie tablice
np.multiply(a,b)

array([ 5, 12, 21, 32])

In [69]:
# metoda do dzielenia
np.divide(a,b)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [70]:
# macierze
x = np.array([[1,3] , [-2 ,0]])
y = np.array([[6,0] , [-1 ,-2]])
print(x , '\n')
print(y)
# 1 * 6 + 3 * 0 itd ...

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1 -2]]


In [71]:
# mnożenie macierzowe wiersz * kolumn
np.dot(x,y)

array([[  3,  -6],
       [-12,   0]])

In [72]:
# 2 spsopob na mnozenie macierzy
x.dot(y)

array([[  3,  -6],
       [-12,   0]])

In [73]:
# uwaga mnożenie macierzy nie jest przemienne
y.dot(y)

array([[36,  0],
       [-4,  4]])

In [74]:
# mnożenie macierzy z algebry liniowej na krzyz albo w zalensoci od rozmirow m x n
x @ y

array([[  3,  -6],
       [-12,   0]])

# Generowanie_liczb_pseudolosowych

In [75]:
np.random.seed(0) # ziarno losowe zawsze uzyskamy ten sam wynik

In [76]:
np.random.randn() # randn - losowy rozklad normalny , zwraca losowy wynik z rozkladu normalnego

1.764052345967664

In [77]:
np.random.randn(10) # 10 wartosci z rozkladu standardowego ze sredniej 0 oraz odchyleniu standarowym 1

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [78]:
# tablica liczb losowych z rozkladu normalnego x na y , przydatne do utworzenia danych losowych np do histogramu
np.random.randn(10,4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [79]:
# rozklad jednostajny na przedziale wartosc z przediali od <0 ,1) , bez jedynki
np.random.rand()

0.1965823616800535

In [80]:
np.random.rand(10) # 10 elemetow

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [81]:
# rozmiar taki jaki przedstawilismy 4 kolumn i 10 wierszy
np.random.rand(10,4 )

array([[0.03918779, 0.28280696, 0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318, 0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145, 0.26538949, 0.52324805],
       [0.09394051, 0.5759465 , 0.9292962 , 0.31856895],
       [0.66741038, 0.13179786, 0.7163272 , 0.28940609],
       [0.18319136, 0.58651293, 0.02010755, 0.82894003],
       [0.00469548, 0.67781654, 0.27000797, 0.73519402],
       [0.96218855, 0.24875314, 0.57615733, 0.59204193],
       [0.57225191, 0.22308163, 0.95274901, 0.44712538],
       [0.84640867, 0.69947928, 0.29743695, 0.81379782]])

In [82]:
# funkcja randint zwraca liczne calkowita oid <x , y) bez y (nie wliczajac y )
np.random.randint(10)

8

In [83]:
# mozemy podac wartosc dolna oraz wartosc gorna <x , y)
np.random.randint(low=4 ,high=12)


4

In [84]:
# modul zawiera funkcje choice , ktory wybiera losowy element z listy
np.random.choice([1,5,7,3,67,3,3])

np.int64(1)

In [85]:
np.random.choice(['xd' , 'lol' , 'nw'])

np.str_('lol')

In [86]:
# funkcja do mieszania danych w kolejnosci
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
np.random.shuffle(data)
data

array([7, 2, 8, 6, 3, 9, 1, 4, 0, 5])

# Podstawowe funkcje

In [88]:
# funkcja wykorzystyawna w seciach neuronowych czyli funkcja eykładnicza e^x
np.exp(1) # e^1 = 2.718281828459045

np.float64(2.718281828459045)

In [89]:
# pierwiastek kwadratowy
np.sqrt(9)

np.float64(3.0)

In [90]:
# all sprawdza kazdy elemnt i sprawdza czy kazda zwróci true to zwróci true wpp zwróci false
print(np.all([1,2,3,4]))
print(np.all([1,2,3,0]))

True
False


In [91]:
# all sprawdza czy jakikolwiek elemnt jest true to zwróci true wpp zwróci false
print(np.any([1,2,3,4]))
print(np.all([1,2,3,0]))

True
False


In [92]:
bool(0)

False

# Indeksowanie , wycinanie

In [93]:
# generowanie danych
A = np.arange(20)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [94]:
# jak wyciac konkretny element poprzez jego indeks zaczyna sie index od zera 0
# A[idx] , A[start : stop] , A[:stop] , A[start:]


In [95]:
# chcac wyciąc 2 element to :
print(A[2])
print(A[2:])
print(A[:2]) # bez uwzglednienia elemntu stopu

2
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 1]


In [96]:
# wycinanie konkretnych elementow
A[[0,2]]


array([0, 2])

In [97]:
# indeksowanie od konca
A[-1] # ostatnia wartosc

np.int64(19)

In [98]:
# od 10(z zawartym 10 elementem)  do 15 elementu (nie zawierajac 15 elementu)
A[10:15]

array([10, 11, 12, 13, 14])

In [99]:
# przeksztalcanie tablicy
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [100]:
# wycianie konkretnych macierzy , kolumn czy wierszy z calosci
#cala kolumna
A[:,0] # [wszystkie_wiersze , 0 element ]

array([ 0,  5, 10, 15])

In [101]:
# wyciecie fragmentu tablicy
A[1, 1:4]

array([6, 7, 8])

In [102]:
# modyfikacja wartosci
A[1:3 , 1:4] = 67
A

array([[ 0,  1,  2,  3,  4],
       [ 5, 67, 67, 67,  9],
       [10, 67, 67, 67, 14],
       [15, 16, 17, 18, 19]])

# Iteracja po tablicach

In [103]:
# przechodzenie po wierszach poprzez petle
for row in A:
    print(row)

[0 1 2 3 4]
[ 5 67 67 67  9]
[10 67 67 67 14]
[15 16 17 18 19]


In [104]:
# przechodzenie po wszystkich elementach , pierwsze elemty
for row in A:
  print(row[0])

0
5
10
15


In [105]:
# trzy pierwsze elementy
for row in A:
  print(row[:3])

[0 1 2]
[ 5 67 67]
[10 67 67]
[15 16 17]


In [106]:
# Iterownie po kazdym elemencie po spłaszczeniu
# flat zwraca iterator, który przechodzi przez wszystkie elementy tablicy
for item in A.flat:
  print(item)

0
1
2
3
4
5
67
67
67
9
10
67
67
67
14
15
16
17
18
19


# Zmiana rozmiaru tablicy

In [107]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5, 67, 67, 67,  9],
       [10, 67, 67, 67, 14],
       [15, 16, 17, 18, 19]])

In [108]:
# ile wierszy na ile kolumn
A.shape

(4, 5)

In [111]:
# zmiana rozmiaru
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5, 67, 67],
       [67,  9, 10, 67],
       [67, 67, 14, 15],
       [16, 17, 18, 19]])

In [113]:
# metoda pozwalajaca wypłaszczac nasze dane czyli powrot do postaci jednowymiarowej
A.ravel()

array([ 0,  1,  2,  3,  4,  5, 67, 67, 67,  9, 10, 67, 67, 67, 14, 15, 16,
       17, 18, 19])

In [114]:
# transponowanie macierzy
A.T


array([[ 0,  5, 10, 15],
       [ 1, 67, 67, 16],
       [ 2, 67, 67, 17],
       [ 3, 67, 67, 18],
       [ 4,  9, 14, 19]])

# Maski Logiczne

In [115]:
A = np.arange(start=-10 , stop=10 , step=0.5)
A = A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [117]:
# sprawdzanie w ktorych miejscach mamy wartosci ujemne
A > 0 # to rownianie zwraca maske logiczne prawda gdu > 0 falsz gdy < 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [121]:
# wyciecie tych elementow ktore spelniaja
A[A > 0 ]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [122]:
# funkcja bitwise_and ktora pozwala na konstruowanie szerokich warunkow
np.bitwise_and(A > -5 , A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [123]:
# bitwise_or - mozmy podac dwa warunki
np.bitwise_or(A < -5 , A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

# Broadcasting