<a href="https://colab.research.google.com/github/Kornel1156/Data-Science/blob/main/01_biblioteka_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Spis Treści :
1. [Podstawy](#scrollTo=Podstawy)
2. [Typy Danych](#scrollTo=Typy_Danych)
3. [Tworzenie Tablic](#scrollTo=Tworzenie_Tablic)
4. [Podstawowe operacje na tablicach](#scrollTo=Podstawowe_operacje_na_tablicach)
5. [Generowanie liczb pseudolosowych](#scrollTo=Generowanie_liczb_pseudolosowych)
6. [Podstawowe funkcje](#scrollTo=Podstawowe_funkcje)
7. [Indeksowanie , wycinanie](#scrollTo=Indeksowanie_wycinanie)
8. [Iteracja po tablicach](#scrollTo=Iteracja_po_tablicach)
9. [Zmiana rozmiaru tablicy](#scrollTo=Zmiana_rozmiaru_tablicy)
10. [Maski](#scrollTo=Maski)
11. [Broadcasting](#scrollTo=Broadcasting)



# Podstawy

In [20]:
import numpy as np                 # importowanie biblioteki numpy
np.__version__                     # sprawdzenie Wersji biblioteki

'2.0.2'

sprawdzenie wszystkich możliwych dubkfju i metod które zawiera biblioteka

In [21]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'arra

aby dowiedziec sie o metodzie albo funkcji która oferuje biblioteka używamy help

In [22]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

1. Podstawowy element biblioteki numpy jest wielowymiarowa tablica

2. cecha charakterystyczna jest jej jednorodny typ tylko taki sam wszystkich elementow

3. osie to wiersze i kolumny czy tez 3 , 4 wymiar w naszym zbiorze , nazywane sa axis



tablica 1D


In [23]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [24]:
print(x)

[1 2 3 4]


In [25]:
type(x) # funkcja type , sprawdza typ obiektu

numpy.ndarray

In [26]:
x.ndim # ilosc wumarow czyli ile wierszy i kolumn albo bardziej wymiarowe przestrzenie danych

1

In [27]:
x.shape # przedstawia ile elementow znajduje sie w kazdym wymiarze n # bo mamy 4 elementy 1 wiersz

(4,)

In [28]:
x.size # liczba wszystkich elementow w calej przestrzeni

4

In [29]:
x.dtype # okresla jakiego typu dane sa reprezentowane przez tablice numpy bo może być tylko jeden konkretny w danym momencie jednakowy typ dla wszystkich


dtype('int64')

In [30]:
x = np.array([1.2,2.3,2.5])

In [31]:
print(x)

[1.2 2.3 2.5]


In [32]:
x.dtype

dtype('float64')

tablica 2D - macierze

In [33]:
x = np.array([[1,2] , [-3 , 1 ]])

In [34]:
x

array([[ 1,  2],
       [-3,  1]])

In [35]:
x.ndim # ilosc wymiarow tablicy

2

In [36]:
x.shape # przedstawia ile elementow znajduje sie w kazdym wymiarze , # bo mamy 1 tablice , 2 kolumny , 2 wiersze

(2, 2)

In [37]:
x.size # calkowita ilosc wartosci

4

In [38]:
x = np.array([[1,2,3],[4,5,6]])

In [39]:
print(x)

[[1 2 3]
 [4 5 6]]


In [40]:
x.shape  # przedstawia ile elementow znajduje sie w kazdym wymiarze

(2, 3)

tablica 3D

In [41]:
x = np.array([
    [[2,3,4],
     [3,5,7]],

    [[4,0,4],
     [4,5,6]],
    ])

In [42]:
x.shape  # ilosc elementow w kazdym wymiarze bo mamy 2 tablice , 2 wiersze , 3 kolumny

(2, 2, 3)

In [43]:
x.ndim

3

In [44]:
x = np.array([
    [[2,3,4],
     [3,5,7]],

    [[4,0,4],
     [4,5,6]],

    [[4,0,4],
     [4,5,6]]
    ])

In [45]:
x.ndim

3

In [46]:
x.shape

(3, 2, 3)

In [47]:
# bo mamy 3 tablice , 2 wiersze , 3 kolumny

# Typy_Danych

Tworzenie tablicy

In [48]:
a = np.array([1.0 , 2.4,3.5])

In [49]:
a.dtype

dtype('float64')

In [50]:
a = np.array([0 ,4,3])

In [51]:
a.dtype

dtype('int64')

* USTAWIENIE DODATKOWEGO PARAMETRU JAKIEGO TYPU JEST TABLICA KTORA AUTOMATYCZNIE USTAWIA NP INT NA FLOAT
* DODATKOWY PARAMETR DZIALA JAK RZUTOWANIE NA WSKAZANY TYP

In [52]:
a = np.array([1, 2,3] , dtype='float') # typ zmiennoprzecinkowy

In [53]:
a

array([1., 2., 3.])

In [54]:
a = np.array([1.895, 2.333,3.345] , dtype='int') # styp staly

In [55]:
a

array([1, 2, 3])

In [56]:
type(a)

numpy.ndarray

In [57]:
a = np.array([1.895, 2.333,3.345] , dtype='complex') # typ urojone

In [58]:
a

array([1.895+0.j, 2.333+0.j, 3.345+0.j])

In [59]:
a.dtype

dtype('complex128')

In [60]:
a = np.array([True , False]) # typ boolowski

In [61]:
a.dtype

dtype('bool')

* (WBUDOWANE TYPY DANYCH jak unisigned int 8 od 0 do 255 ) Tablica reprezentujaca obraz dla pixeli

In [62]:
a = np.array([24,120 , 230] , dtype=np.uint8)

# Tworzenie_Tablic

In [63]:
np.zeros(shape=(4,10)) # tworzy dowolna tablica utworzoną z samych zer

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Dodanie z okresleniem typow naszych wartosci w takiej tablicy

In [64]:
np.zeros(shape=(4,10) , dtype='int') # tworzy dowolna tablica utworzoną z samych zer z typem

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

tablica z samymi jedynkami

In [65]:
np.ones(shape=(5,5) ,  dtype='complex')

array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]])

tworzenie tablic z wartosciami ktore my chcemy

In [66]:
np.full(shape=(4,10) , fill_value=4 , dtype='double') # tworzy dowolna tablica utworzoną z samych zer z typem oraz nasza wartscia

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

wygeneruje dane w zakresie

In [67]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

ustawienie poczatek koniec i co ile

In [68]:
np.arange(start=5 , stop=12)

array([ 5,  6,  7,  8,  9, 10, 11])

In [69]:
np.arange(start=1 , stop=12 , step=3) # dodatkowy parametr definiujacy krok z jakim tworzona jest tablica

array([ 1,  4,  7, 10])

In [70]:
np.arange(start=100 , stop=0 , step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [71]:
np.arange(start=1 , stop=0 , step=-0.02)

array([1.  , 0.98, 0.96, 0.94, 0.92, 0.9 , 0.88, 0.86, 0.84, 0.82, 0.8 ,
       0.78, 0.76, 0.74, 0.72, 0.7 , 0.68, 0.66, 0.64, 0.62, 0.6 , 0.58,
       0.56, 0.54, 0.52, 0.5 , 0.48, 0.46, 0.44, 0.42, 0.4 , 0.38, 0.36,
       0.34, 0.32, 0.3 , 0.28, 0.26, 0.24, 0.22, 0.2 , 0.18, 0.16, 0.14,
       0.12, 0.1 , 0.08, 0.06, 0.04, 0.02])

linspace funkcja ktora tworzy nam zbior wartosci z przedziału początek i koniec który bedzie zawierał rowno podzielone wartosci wedug parametru ilosci przedziałów

* reasumujac dodstniemy num=x wartosci rowno rozlozonych z przedzialu start=a , stop=b

In [72]:
np.linspace(start=0 , stop=1 , num=13)

array([0.        , 0.08333333, 0.16666667, 0.25      , 0.33333333,
       0.41666667, 0.5       , 0.58333333, 0.66666667, 0.75      ,
       0.83333333, 0.91666667, 1.        ])

zmienianiu rozmiaru danych

In [73]:
a = np.arange(15)

In [74]:
a.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [75]:
a.reshape((3, -1)) # -1 do odpowiednia liczba kolumn jaka musi byc czyli python sam dostosuje poprzez -1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [76]:
a.reshape((-1, 3)) # -1 do odpowiednia liczba kolumn jaka musi byc czyli python sam dostosuje poprzez -1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# Podstawowe operacje na tablicach

In [77]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [78]:
a + b # dodawanie element po elemencie

array([ 6,  8, 10, 12])

In [79]:
a - b # odejmowanie element po elemencie

array([-4, -4, -4, -4])

In [80]:
a * b


array([ 5, 12, 21, 32])

In [81]:
a / b  # uwaaga nie mozna dzielic przez 0 wiec tablica nie moze miec zera w mianowniku

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [82]:
# dodanie 3 do kazdego elementu
a + 3


array([4, 5, 6, 7])

In [83]:
# inne i łączone
a + 3*  b

array([16, 20, 24, 28])

In [84]:
# rowniez metody ktore dodaja dwie tablice
np.add(a,b)

array([ 6,  8, 10, 12])

In [85]:
# odejmowanie przez metode
np.subtract(a,b)

array([-4, -4, -4, -4])

In [86]:
# metoda mnożaca dwie tablice
np.multiply(a,b)

array([ 5, 12, 21, 32])

In [87]:
# metoda do dzielenia
np.divide(a,b)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [88]:
# macierze
x = np.array([[1,3] , [-2 ,0]])
y = np.array([[6,0] , [-1 ,-2]])
print(x , '\n')
print(y)
# 1 * 6 + 3 * 0 itd ...

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1 -2]]


In [89]:
# mnożenie macierzowe wiersz * kolumn
np.dot(x,y)

array([[  3,  -6],
       [-12,   0]])

In [90]:
# 2 spsopob na mnozenie macierzy
x.dot(y)

array([[  3,  -6],
       [-12,   0]])

In [91]:
# uwaga mnożenie macierzy nie jest przemienne
y.dot(y)

array([[36,  0],
       [-4,  4]])

In [92]:
# mnożenie macierzy z algebry liniowej na krzyz albo w zalensoci od rozmirow m x n
x @ y

array([[  3,  -6],
       [-12,   0]])

# Generowanie_liczb_pseudolosowych

In [93]:
np.random.seed(0) # ziarno losowe zawsze uzyskamy ten sam wynik

In [94]:
np.random.randn() # randn - losowy rozklad normalny , zwraca losowy wynik z rozkladu normalnego

1.764052345967664

In [95]:
np.random.randn(10) # 10 wartosci z rozkladu standardowego ze sredniej 0 oraz odchyleniu standarowym 1

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [96]:
# tablica liczb losowych z rozkladu normalnego x na y , przydatne do utworzenia danych losowych np do histogramu
np.random.randn(10,4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [97]:
# rozklad jednostajny na przedziale wartosc z przediali od <0 ,1) , bez jedynki
np.random.rand()

0.1965823616800535

In [98]:
np.random.rand(10) # 10 elemetow

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [99]:
# rozmiar taki jaki przedstawilismy 4 kolumn i 10 wierszy
np.random.rand(10,4 )

array([[0.03918779, 0.28280696, 0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318, 0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145, 0.26538949, 0.52324805],
       [0.09394051, 0.5759465 , 0.9292962 , 0.31856895],
       [0.66741038, 0.13179786, 0.7163272 , 0.28940609],
       [0.18319136, 0.58651293, 0.02010755, 0.82894003],
       [0.00469548, 0.67781654, 0.27000797, 0.73519402],
       [0.96218855, 0.24875314, 0.57615733, 0.59204193],
       [0.57225191, 0.22308163, 0.95274901, 0.44712538],
       [0.84640867, 0.69947928, 0.29743695, 0.81379782]])

In [100]:
# funkcja randint zwraca liczne calkowita oid <x , y) bez y (nie wliczajac y )
np.random.randint(10)

8

In [101]:
# mozemy podac wartosc dolna oraz wartosc gorna <x , y)
np.random.randint(low=4 ,high=12)


4

In [102]:
# modul zawiera funkcje choice , ktory wybiera losowy element z listy
np.random.choice([1,5,7,3,67,3,3])

np.int64(1)

In [103]:
np.random.choice(['xd' , 'lol' , 'nw'])

np.str_('lol')

In [104]:
# funkcja do mieszania danych w kolejnosci
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
np.random.shuffle(data)
data

array([7, 2, 8, 6, 3, 9, 1, 4, 0, 5])

# Podstawowe funkcje

In [106]:
# funkcja wykorzystyawna w seciach neuronowych czyli funkcja eykładnicza e^x
np.exp(1) # e^1 = 2.718281828459045

np.float64(2.718281828459045)

In [107]:
# pierwiastek kwadratowy
np.sqrt(9)

np.float64(3.0)

In [110]:
# all sprawdza kazdy elemnt i sprawdza czy kazda zwróci true to zwróci true wpp zwróci false
print(np.all([1,2,3,4]))
print(np.all([1,2,3,0]))

True
False


In [113]:
# all sprawdza czy jakikolwiek elemnt jest true to zwróci true wpp zwróci false
print(np.any([1,2,3,4]))
print(np.all([1,2,3,0]))

True
False


In [ ]:
# funkcja bool dla 0 zwroci false a dla kazdej innej liczby zwróci true
bool(0)

In [118]:
# funkcja generujaca wartosci z rozkładu normalnego 5 roznych wartosci
print(np.random.randn(5))
# funkcja generujaca wartosci z rozkładu jednostajnego 5 roznych wartosci
print(np.random.rand(5))

[-2.04038084  0.25973465 -1.68134864 -0.91679481 -0.1192241 ]
[0.35231166 0.46924917 0.84114013 0.90464774 0.03755938]


In [135]:
# przyjmijmy ze wynik tego to prawdopodobienstwo otrzymania poszczegolnej klasy dla danej probki
# czyli mamy probelm klasyfikacji mamy 5 klas i chcemy je przyporzadkowac , model zwrocil wartosci prawdopodobienstw
A = np.random.rand(5)
print(A)
# sprobujmy uzyc funkcji ktora zwróci nam indeks elementu gdzie nasza tablica przyjmuje wartosi najwieksza
print(np.argmax(A))
# chcac wyciac tą wartosc z naszej tablicy użyjemy :
print(A[np.argmax(A)])
# równiez jest funkcja zwracająca wartosc najniższą
print(np.argmin(A))
# jezeli mamy klasyfikacje wieloklasową to mozemy posortowac prawdopodobienstawa ktora sortuje wskazujac indeksami elemntu od min do max poprzez :
# czyli jesli chcemy przedstawic wedle najwiekszego prawdopodobienstwa elemntu do danej klasyfikacji
print(np.argsort(A))

[0.71158382 0.15369431 0.73044218 0.64626444 0.21488074]
2
0.7304421765667943
1
[1 4 3 0 2]


In [140]:
# bardziej statystyczne
# maksimum
print(np.max(A))
# minimum
print(np.min(A))


0.7304421765667943
0.15369430500779646


In [141]:
# srednia
np.mean(A)

np.float64(0.4913730945401336)

In [142]:
# mediana
np.median(A)

np.float64(0.6462644373146849)

In [143]:
# odchylenie standardowe
np.std(A)

np.float64(0.2530269176102439)

# Indeksowanie , wycinanie

# Iteracja po tablicach

# Zmiana rozmiaru tablicy

# Maski

# Broadcasting