<a href="https://colab.research.google.com/github/Kornel1156/Data-Science/blob/main/01_biblioteka_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Spis Treści :
1. [Podstawy](#a1)
1. [Typy Danych](#a2)


# Podstawy

In [1]:
import numpy as np                 # importowanie biblioteki numpy
np.__version__                     # sprawdzenie Wersji biblioteki

'2.0.2'

sprawdzenie wszystkich możliwych dubkfju i metod które zawiera biblioteka

In [2]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'arra

aby dowiedziec sie o metodzie albo funkcji która oferuje biblioteka używamy help

In [3]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

1. Podstawowy element biblioteki numpy jest wielowymiarowa tablica

2. cecha charakterystyczna jest jej jednorodny typ tylko taki sam wszystkich elementow

3. osie to wiersze i kolumny czy tez 3 , 4 wymiar w naszym zbiorze , nazywane sa axis



tablica 1D


In [4]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [5]:
print(x)

[1 2 3 4]


In [6]:
type(x) # funkcja type , sprawdza typ obiektu

numpy.ndarray

In [7]:
x.ndim # ilosc wumarow czyli ile wierszy i kolumn albo bardziej wymiarowe przestrzenie danych

1

In [8]:
x.shape # przedstawia ile elementow znajduje sie w kazdym wymiarze n # bo mamy 4 elementy 1 wiersz

(4,)

In [9]:
x.size # liczba wszystkich elementow w calej przestrzeni

4

In [10]:
x.dtype # okresla jakiego typu dane sa reprezentowane przez tablice numpy bo może być tylko jeden konkretny w danym momencie jednakowy typ dla wszystkich


dtype('int64')

In [11]:
x = np.array([1.2,2.3,2.5])

In [12]:
print(x)

[1.2 2.3 2.5]


In [13]:
x.dtype

dtype('float64')

tablica 2D - macierze

In [14]:
x = np.array([[1,2] , [-3 , 1 ]])

In [15]:
x

array([[ 1,  2],
       [-3,  1]])

In [16]:
x.ndim # ilosc wymiarow tablicy

2

In [17]:
x.shape # przedstawia ile elementow znajduje sie w kazdym wymiarze , # bo mamy 1 tablice , 2 kolumny , 2 wiersze

(2, 2)

In [18]:
x.size # calkowita ilosc wartosci

4

In [19]:
x = np.array([[1,2,3],[4,5,6]])

In [20]:
print(x)

[[1 2 3]
 [4 5 6]]


In [21]:
x.shape  # przedstawia ile elementow znajduje sie w kazdym wymiarze

(2, 3)

tablica 3D

In [22]:
x = np.array([
    [[2,3,4],
     [3,5,7]],

    [[4,0,4],
     [4,5,6]],
    ])

In [23]:
|

SyntaxError: invalid syntax (525519296.py, line 1)

In [ ]:
x.shape  # ilosc elementow w kazdym wymiarze bo mamy 2 tablice , 2 wiersze , 3 kolumny

In [ ]:
x.ndim

In [ ]:
x = np.array([
    [[2,3,4],
     [3,5,7]],

    [[4,0,4],
     [4,5,6]],

    [[4,0,4],
     [4,5,6]]
    ])

In [ ]:
x.ndim

In [ ]:
x.shape

In [ ]:
# bo mamy 3 tablice , 2 wiersze , 3 kolumny

# Typy Danych

Tworzenie tablicy

In [26]:
a = np.array([1.0 , 2.4,3.5])

In [27]:
a.dtype

dtype('float64')

In [28]:
a = np.array([0 ,4,3])

In [29]:
a.dtype

dtype('int64')

* USTAWIENIE DODATKOWEGO PARAMETRU JAKIEGO TYPU JEST TABLICA KTORA AUTOMATYCZNIE USTAWIA NP INT NA FLOAT
* DODATKOWY PARAMETR DZIALA JAK RZUTOWANIE NA WSKAZANY TYP

In [30]:
a = np.array([1, 2,3] , dtype='float') # typ zmiennoprzecinkowy

In [31]:
a

array([1., 2., 3.])

In [32]:
a = np.array([1.895, 2.333,3.345] , dtype='int') # styp staly

In [33]:
a

array([1, 2, 3])

In [35]:
type(a)

numpy.ndarray

In [36]:
a = np.array([1.895, 2.333,3.345] , dtype='complex') # typ urojone

In [37]:
a

array([1.895+0.j, 2.333+0.j, 3.345+0.j])

In [38]:
a.dtype

dtype('complex128')

In [39]:
a = np.array([True , False]) # typ boolowski

In [40]:
a.dtype

dtype('bool')

* (WBUDOWANE TYPY DANYCH jak unisigned int 8 od 0 do 255 ) Tablica reprezentujaca obraz dla pixeli

In [ ]:
a = np.array([24,120 , 230] , dtype=np.uint8)