<a href="https://colab.research.google.com/github/Kornel1156/Data-Science/blob/main/01_biblioteka_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Spis Treści :
1. [Podstawy](#scrollTo=Podstawy)
2. [Typy Danych](#scrollTo=Typy_Danych)
3. [Tworzenie Tablic](#scrollTo=Tworzenie_Tablic)


# Podstawy

In [2]:
import numpy as np                 # importowanie biblioteki numpy
np.__version__                     # sprawdzenie Wersji biblioteki

'2.0.2'

sprawdzenie wszystkich możliwych dubkfju i metod które zawiera biblioteka

In [3]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'arra

aby dowiedziec sie o metodzie albo funkcji która oferuje biblioteka używamy help

In [4]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

1. Podstawowy element biblioteki numpy jest wielowymiarowa tablica

2. cecha charakterystyczna jest jej jednorodny typ tylko taki sam wszystkich elementow

3. osie to wiersze i kolumny czy tez 3 , 4 wymiar w naszym zbiorze , nazywane sa axis



tablica 1D


In [5]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [6]:
print(x)

[1 2 3 4]


In [7]:
type(x) # funkcja type , sprawdza typ obiektu

numpy.ndarray

In [8]:
x.ndim # ilosc wumarow czyli ile wierszy i kolumn albo bardziej wymiarowe przestrzenie danych

1

In [9]:
x.shape # przedstawia ile elementow znajduje sie w kazdym wymiarze n # bo mamy 4 elementy 1 wiersz

(4,)

In [10]:
x.size # liczba wszystkich elementow w calej przestrzeni

4

In [11]:
x.dtype # okresla jakiego typu dane sa reprezentowane przez tablice numpy bo może być tylko jeden konkretny w danym momencie jednakowy typ dla wszystkich


dtype('int64')

In [12]:
x = np.array([1.2,2.3,2.5])

In [13]:
print(x)

[1.2 2.3 2.5]


In [14]:
x.dtype

dtype('float64')

tablica 2D - macierze

In [15]:
x = np.array([[1,2] , [-3 , 1 ]])

In [16]:
x

array([[ 1,  2],
       [-3,  1]])

In [17]:
x.ndim # ilosc wymiarow tablicy

2

In [18]:
x.shape # przedstawia ile elementow znajduje sie w kazdym wymiarze , # bo mamy 1 tablice , 2 kolumny , 2 wiersze

(2, 2)

In [19]:
x.size # calkowita ilosc wartosci

4

In [20]:
x = np.array([[1,2,3],[4,5,6]])

In [21]:
print(x)

[[1 2 3]
 [4 5 6]]


In [22]:
x.shape  # przedstawia ile elementow znajduje sie w kazdym wymiarze

(2, 3)

tablica 3D

In [23]:
x = np.array([
    [[2,3,4],
     [3,5,7]],

    [[4,0,4],
     [4,5,6]],
    ])

In [24]:
x.shape  # ilosc elementow w kazdym wymiarze bo mamy 2 tablice , 2 wiersze , 3 kolumny

(2, 2, 3)

In [25]:
x.ndim

3

In [26]:
x = np.array([
    [[2,3,4],
     [3,5,7]],

    [[4,0,4],
     [4,5,6]],

    [[4,0,4],
     [4,5,6]]
    ])

In [27]:
x.ndim

3

In [28]:
x.shape

(3, 2, 3)

In [29]:
# bo mamy 3 tablice , 2 wiersze , 3 kolumny

# Typy_Danych

Tworzenie tablicy

In [30]:
a = np.array([1.0 , 2.4,3.5])

In [31]:
a.dtype

dtype('float64')

In [32]:
a = np.array([0 ,4,3])

In [33]:
a.dtype

dtype('int64')

* USTAWIENIE DODATKOWEGO PARAMETRU JAKIEGO TYPU JEST TABLICA KTORA AUTOMATYCZNIE USTAWIA NP INT NA FLOAT
* DODATKOWY PARAMETR DZIALA JAK RZUTOWANIE NA WSKAZANY TYP

In [34]:
a = np.array([1, 2,3] , dtype='float') # typ zmiennoprzecinkowy

In [35]:
a

array([1., 2., 3.])

In [36]:
a = np.array([1.895, 2.333,3.345] , dtype='int') # styp staly

In [37]:
a

array([1, 2, 3])

In [38]:
type(a)

numpy.ndarray

In [39]:
a = np.array([1.895, 2.333,3.345] , dtype='complex') # typ urojone

In [40]:
a

array([1.895+0.j, 2.333+0.j, 3.345+0.j])

In [41]:
a.dtype

dtype('complex128')

In [42]:
a = np.array([True , False]) # typ boolowski

In [43]:
a.dtype

dtype('bool')

* (WBUDOWANE TYPY DANYCH jak unisigned int 8 od 0 do 255 ) Tablica reprezentujaca obraz dla pixeli

In [44]:
a = np.array([24,120 , 230] , dtype=np.uint8)

# Tworzenie_Tablic

In [45]:
np.zeros(shape=(4,10)) # tworzy dowolna tablica utworzoną z samych zer

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Dodanie z okresleniem typow naszych wartosci w takiej tablicy

In [47]:
np.zeros(shape=(4,10) , dtype='int') # tworzy dowolna tablica utworzoną z samych zer z typem

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

tablica z samymi jedynkami

In [49]:
np.ones(shape=(5,5) ,  dtype='complex')

array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]])

tworzenie tablic z wartosciami ktore my chcemy

In [51]:
np.full(shape=(4,10) , fill_value=4 , dtype='double') # tworzy dowolna tablica utworzoną z samych zer z typem oraz nasza wartscia

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

wygeneruje dane w zakresie

In [54]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

ustawienie poczatek koniec i co ile

In [55]:
np.arange(start=5 , stop=12)

array([ 5,  6,  7,  8,  9, 10, 11])

In [57]:
np.arange(start=1 , stop=12 , step=3) # dodatkowy parametr definiujacy krok z jakim tworzona jest tablica

array([ 1,  4,  7, 10])

In [59]:
np.arange(start=100 , stop=0 , step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [61]:
np.arange(start=1 , stop=0 , step=-0.02)

array([1.  , 0.98, 0.96, 0.94, 0.92, 0.9 , 0.88, 0.86, 0.84, 0.82, 0.8 ,
       0.78, 0.76, 0.74, 0.72, 0.7 , 0.68, 0.66, 0.64, 0.62, 0.6 , 0.58,
       0.56, 0.54, 0.52, 0.5 , 0.48, 0.46, 0.44, 0.42, 0.4 , 0.38, 0.36,
       0.34, 0.32, 0.3 , 0.28, 0.26, 0.24, 0.22, 0.2 , 0.18, 0.16, 0.14,
       0.12, 0.1 , 0.08, 0.06, 0.04, 0.02])

linspace funkcja ktora tworzy nam zbior wartosci z przedziału początek i koniec który bedzie zawierał rowno podzielone wartosci wedug parametru ilosci przedziałów

* reasumujac dodstniemy num=x wartosci rowno rozlozonych z przedzialu start=a , stop=b

In [65]:
np.linspace(start=0 , stop=1 , num=13)

array([0.        , 0.08333333, 0.16666667, 0.25      , 0.33333333,
       0.41666667, 0.5       , 0.58333333, 0.66666667, 0.75      ,
       0.83333333, 0.91666667, 1.        ])

zmienianiu rozmiaru danych

In [66]:
a = np.arange(15)

In [68]:
a.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [70]:
a.reshape((3, -1)) # -1 do odpowiednia liczba kolumn jaka musi byc czyli python sam dostosuje poprzez -1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [71]:
a.reshape((-1, 3)) # -1 do odpowiednia liczba kolumn jaka musi byc czyli python sam dostosuje poprzez -1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])