<a href="https://colab.research.google.com/github/Kornel1156/Data-Science/blob/main/1_NumPy/03_funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Funkcje statystyczne

In [13]:
import numpy as np
np.__version__

'2.0.2'

In [14]:
# cena na giełdzie z ostanich 3 dni
# | open | hight | low | close | volumen |
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


sum()

In [15]:
# suma wszystkich elementow ktore znajduja sie w tablicy
price.sum()

np.float64(4650.1)

In [16]:
price.sum(axis=0)# sumuje w osi pionowej w osi Y czyli podaje sumy kolumn z osobna

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [17]:
price.sum(axis=1) # sumuje wartosci z wierszy X

array([1049.7, 2049.4, 1551. ])

In [18]:
np.sum(price) # całkowita suma naszej tabeli

np.float64(4650.1)

min()

In [19]:
np.min(price, axis=0) # minimalna wartosc z kolumn z wymiaru kolumn y

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

max()

In [20]:
np.max(price, axis=0) # maksmyalne wartiscu ze wszystkuch kolumn

array([  12.5,   13.4,   12.2,   13.2, 2000. ])

median()

In [21]:
np.median(price)

np.float64(12.6)

mean() # średnia wymiarow

In [22]:
np.mean(price, axis=0)

array([  12.36666667,   13.06666667,   11.93333333,   12.66666667,
       1500.        ])

std() # miara rozrzutu czyli odchylenie standardowe . Odchylenie standardowe jest w tej samej skali i jednostce co dane. Jeśli mierzysz wzrost w centymetrach, odchylenie standardowe również jest wyrażone w centymetrach. Dzięki temu można powiedzieć np.:

„Wyniki odbiegają od średniej przeciętnie o około 5 cm.”

In [23]:
np.std(price, axis=0)

array([1.24721913e-01, 2.49443826e-01, 2.05480467e-01, 4.10960934e-01,
       4.08248290e+02])

var() # Wariancja to miara rozproszenia danych. Mówi nam, jak bardzo wartości w zbiorze różnią się od średniej.
Wariancja nie jest w tej samej skali, ponieważ podczas jej obliczania odchylenia od średniej są podnoszone do kwadratu. Dlatego jednostką wariancji są cm², kg², punkty² itd. To sprawia, że jej interpretacja jest mniej intuicyjna.

In [24]:
np.var(price, axis=0)

array([1.55555556e-02, 6.22222222e-02, 4.22222222e-02, 1.68888889e-01,
       1.66666667e+05])